---
- hosts: server
  user: ranjan
  become: yes
  connection: ssh
  tasks:
    - name: copy
      copy:
        src: project_rajesh/
        dest: /var/www/html/django/project
        mode: 0644
        backup: true
        
